- name: set timezone to {{ zone }}
  timezone:
    name: "{{ zone }}"

- name: set locale {{ keymap }}
  shell: localectl set-keymap {{ keymap }}
  register: set_locale
  changed_when: False

- name: remove postfix
  yum: name=postfix state=absent

- name: install wget/git/libselinux-python/epel
  yum:
    name:
      - wget
      - git
      - libselinux-python
      - epel-release
    state: latest

- name: disable SELinux
  selinux: state=disabled

- name: remove firewalld
  yum: name=firewalld state=absent

- name: sysctl.conf vm.swappiness 1
  sysctl: name="vm.swappiness" value=1 state=present

- name: sysctl.conf disable ipv6
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1

- name: add alias
  shell: echo "alias lr='ls -lahtr'" >> /root/.bashrc

- name: sshd_config PermitRootLogin yes
  lineinfile:
    dest:     /etc/ssh/sshd_config
    state:    present
    backrefs: yes
    regexp:   '^#PermitRootLogin yes'
    line:     'PermitRootLogin yes'

- name: sshd_config PasswordAuthentication yes
  lineinfile:
    dest:     /etc/ssh/sshd_config
    state:    present
    backrefs: yes
    regexp:   '^#PasswordAuthentication yes'
    line:     'PasswordAuthentication yes'

- name: sshd_config delete PasswordAuthentication no
  lineinfile:
    dest:     /etc/ssh/sshd_config
    state:    present
    backrefs: yes
    regexp:   '^PasswordAuthentication no'
    line:     ''

- name: restart sshd
  systemd: name=sshd state=restarted

- name: copy /etc/hosts
  copy: src=hosts dest=/etc/hosts

- import_tasks: mariadb-centos7.yml
  when: is_db_node|bool
