- name: remove MariaDB 5.5 libs
  yum: name="mariadb-libs" state=absent

- name: install MariaDB Server {{ mdb_version }} repository
  yum_repository:
    name:        mariadb
    description: MariaDB
    baseurl:     https://downloads.mariadb.com/MariaDB/mariadb-10.4/yum/rhel/$releasever/$basearch
    gpgkey:      https://downloads.mariadb.com/MariaDB/RPM-GPG-KEY-MariaDB
    gpgcheck:    1

- name: MariaDB Server {{ mdb_version }} RPM tar ball exists ?
  stat: path=/vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
  register: rpmtar

- name: rpmtar
  debug:
    msg: rpmtar {{ rpmtar.stat.exists }}

- name: unarchive RPM tarball
  unarchive:
    src:  /vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
    dest: /root
  when: rpmtar.stat.exists

# - name: extract RPM tar ball and install
#   shell: |
#     yum -y localinstall MariaDB-server-{{ mdb_version }}-*.rpm \
#                         MariaDB-client-{{ mdb_version }}-*.rpm \
#                         MariaDB-common-{{ mdb_version }}-*.rpm \
#                         MariaDB-compat-{{ mdb_version }}-*.rpm
#   args:
#     chdir: /root/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms
#   when: rpmtar.stat.exists

- name: install MariaDB Server from repository
  yum: name=MariaDB-server state=latest update_cache=yes
