- name: remove MariaDB 5.5 libs
  yum: name="mariadb-libs" state=absent

- name: install MariaDB Server {{ mdb_version }} repository
  yum_repository:
    name:        mariadb
    description: MariaDB
    baseurl:     https://downloads.mariadb.com/MariaDB/mariadb-10.4/yum/rhel/$releasever/$basearch
    gpgkey:      https://downloads.mariadb.com/MariaDB/RPM-GPG-KEY-MariaDB
    gpgcheck:    1

- name: install MariaDB Server from repository
  yum: name=MariaDB-server state=latest update_cache=yes
