- name: remove MariaDB 5.5 libs
  yum: name="mariadb-libs" state=absent

- name: install MariaDB {{ mdb_version }} repository
  yum_repository:
    name:        mariadb
    description: MariaDB
    baseurl:     https://downloads.mariadb.com/MariaDB/mariadb-10.3/yum/rhel/$releasever/$basearch
    gpgkey:      https://downloads.mariadb.com/MariaDB/RPM-GPG-KEY-MariaDB
    gpgcheck:    1

- name: MariaDB {{ mdb_version }} RPM tar ball exists ?
  stat: path=/vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
  register: rpmtar

- name: extract RPM tar ball and install
  shell: |
    tar xf /vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
    cd /root/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms
    yum -y localinstall MariaDB-{{ mdb_version }}-*-x86_64-server.rpm \
                        MariaDB-{{ mdb_version }}-*-client.rpm \
                        MariaDB-{{ mdb_version }}-*-common.rpm \
                        MariaDB-{{ mdb_version }}-*-compat.rpm
  args:
    chdir: /root
  when: rpmtar.stat.exists

- name: install MariaDB Server from repository
  yum: name=MariaDB-server state=latest update_cache=yes
  when: not rpmtar.stat.exists
