- name: remove MariaDB 5.5 libs
  yum: name="mariadb-libs" state=absent

- name: install MariaDB 10.2 repository
  yum_repository:
    name:        mariadb
    description: MariaDB
    baseurl:     http://yum.mariadb.org/10.2/centos7-amd64
    gpgkey:      https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck:    1

- name: MariaDB 10.2 RPM tar ball exists ?
  stat: path=/vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
  register: rpmtar

- name: extract RPM tar ball and install
  shell: |
    tar xf /vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
    cd /root/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms
    yum -y localinstall MariaDB-{{ mdb_version }}-centos73-x86_64-server.rpm \
                        MariaDB-{{ mdb_version }}-centos73-x86_64-client.rpm \
                        MariaDB-{{ mdb_version }}-centos73-x86_64-common.rpm \
                        MariaDB-{{ mdb_version }}-centos73-x86_64-compat.rpm
  args:
    chdir: /root
  when: rpmtar.stat.exists

- name: install MariaDB Server from repository
  yum: name=MariaDB-server state=latest update_cache=yes
  when: not rpmtar.stat.exists
