- name: MariaDB Package Repository Setup
  shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash

- name: install MaxScale 2.1
  yum: name=maxscale state=latest update_cache=yes

- name: copy maxscale configuration
  copy: src=maxscale.cnf dest=/etc/maxscale.cnf

- name: copy ~/.bash_history
  copy: src=bash_history dest=/root/.bash_history

- name: enable/start MaxScale
  systemd: name=maxscale state=restarted enabled=True
