- name: copy configuration for primary
  template: src=primary.cnf dest=/etc/my.cnf.d/server.cnf

- name: enable/start MariaDB Server(primary)
  systemd: name=mariadb state=started enabled=True

- name: install MYSQL-python
  yum: name=MySQL-python state=present

- name: grant REPLICATION SLAVE to 'repl' user on Primary
  mysql_user: name=repl host=% password=replpwd priv='*.*:REPLICATION CLIENT,REPLICATION SLAVE' state=present

- name: create maxuser@'%' user
  mysql_user:
    name: maxuser
    host: '%'
    password: maxpwd
    priv:  'mysql.user:SELECT/mysql.db:SELECT/mysql.tables_priv:SELECT/mysql.roles_mapping:SELECT/*.*:SHOW DATABASES,REPLICATION CLIENT,REPLICATION SLAVE,SUPER,RELOAD'
    state: present
# https://mariadb.com/kb/en/mariadb-maxscale-24-setting-up-mariadb-maxscale/
# https://mariadb.com/kb/en/mariadb-maxscale-24-mariadb-monitor/

- name: copy .bash_history
  copy: src=bash_history dest=/root/.bash_history

- name: copy .mysql_history
  copy: src=mysql_history dest=/root/.mysql_history
