- name: stop slave
  mysql_replication: mode=stopslave

- name: reset slave
  mysql_replication: mode=resetslave

- name: select @@global.gtid_current_pos of Primary
  command: mysql -h {{ primary_initial }} -u repl --password=replpwd -e "select @@global.gtid_current_pos;"
  register: current_pos

- debug: var=current_pos.stdout_lines[1]

- name: set global GTID position
  command: mysql -e "set global gtid_slave_pos = '{{ current_pos.stdout_lines[1] }}';"

- name: stop slave
  mysql_replication: mode=stopslave

- name: change master
  command: mysql -e "CHANGE MASTER TO MASTER_HOST='{{ primary_initial }}',MASTER_USE_GTID=slave_pos,MASTER_USER='repl',MASTER_PASSWORD='replpwd';"

- name: start slave
  mysql_replication: mode=startslave

- name: get slave
  mysql_replication: mode=getslave
  register: slave_status

- debug: var=slave_status.Gtid_IO_Pos
