# provision MaxScale / Master Slaves
- hosts: all
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  become: yes
  user: vagrant
  roles:
    - common

- hosts: maxscale
  become: yes
  user: vagrant
  roles:
    - maxscale

- hosts: master
  become: yes
  user: vagrant
  roles:
    - master

- hosts: slave1,slave2
  become: yes
  user: vagrant
  roles:
    - slave
