# provision MaxScale / Master / Slaves
- hosts: all
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  become: yes
  user: vagrant
  roles:
    - common

- hosts: mxs1,mxs2
  become: yes
  user: vagrant
  roles:
    - maxscale

- hosts: server1
  become: yes
  user: vagrant
  roles:
    - master

- hosts: server2,server3
  become: yes
  user: vagrant
  roles:
    - slave

- hosts: server1
  become: yes
  user: vagrant
  roles:
    - populate
