- name: MaxScale 2.2 rpm exists ?
  stat: path=/vagrant/maxscale-{{ version }}-1.rhel.7.x86_64.rpm
  register: maxscalerpm

- name: extract RPM tar ball and install
  shell: |
    cp /vagrant/maxscale-{{ version }}-1.rhel.7.x86_64.rpm .
    yum -y localinstall maxscale-{{ version }}-1.rhel.7.x86_64.rpm
  args:
    chdir: /root
  when: maxscalerpm.stat.exists

- name: add maxscale group
  group: name=maxscale state=present

- name: add maxscale user
  user: name=maxscale group=maxscale shell=/sbin/nologin

- name: copy MaxScale configuration
  copy: src=maxscale.cnf dest=/etc/maxscale.cnf

- name: enable/start MaxScale
  systemd: name=maxscale state=started enabled=True

- name: copy ~/.bash_history
  copy: src=bash_history dest=/root/.bash_history
