- name: set up latest MaxScale repository
  yum_repository:
    name:        mariadb-maxscale
    description: MariaDB MaxScale
    baseurl:     https://downloads.mariadb.com/MaxScale/2.4/centos/$releasever/$basearch
    gpgkey:      https://downloads.mariadb.com/MaxScale/MariaDB-MaxScale-GPG-KEY
    gpgcheck:    1

- name: MaxScale {{ mxs_version }} rpm exists ?
  stat: path=/vagrant/maxscale-{{ mxs_version }}-1.centos.7.x86_64.rpm
  register: maxscalerpm

- name: copy RPM and install
  shell: |
    cp /vagrant/maxscale-{{ mxs_version }}-*.rpm .
    yum -y localinstall maxscale-{{ mxs_version }}-*.rpm
  args:
    chdir: /root
  when: maxscalerpm.stat.exists

- name: install MaxScale from MariaDB repository
  yum:  name=maxscale state=latest
  when: not maxscalerpm.stat.exists

- name: copy maxscale.conf
  template: src=maxscale.cnf dest=/etc/maxscale.cnf

- name: copy masking_rules.json
  copy: src=masking_rules.json dest=/etc/maxscale.modules.d/masking_rules.json

- name: enable/start MaxScale
  systemd: name=maxscale state=started enabled=True

- name: copy ~/.bash_history
  copy: src=bash_history dest=/root/.bash_history

- name: copy ~vagrant/.bash_history
  copy:
    src:   bash_history
    dest:  /home/vagrant/.bash_history
    owner: vagrant
    group: vagrant
    mode:  644

- name: copy ~/.mysql_history
  copy: src=mysql_history dest=/root/.mysql_history

- name: install keepalived
  yum:  name=keepalived state=latest

- name: copy keepalived.conf
  template: src=keepalived.conf dest=/etc/keepalived/keepalived.conf

- name: copy is_maxscale_running.sh
  copy: src=is_maxscale_running.sh dest=/home/vagrant/is_maxscale_running.sh mode=0755

- name: enable/start Keepalived
  systemd: name=keepalived state=started enabled=True
